-- QuestSystem.lua (Shared ModuleScript)
-- Quest definitions and config for the NPC quest system

local QuestSystem = {}

QuestSystem.Quests = {
	-- Beginner quests
	{
		Id = "mine_stone_10",
		Name = "Getting Started",
		Description = "Mine 10 Stone blocks",
		NPC = "Miner Mike",
		Type = "Mine",
		Target = "Stone",
		Amount = 10,
		Reward = { Cash = 50 },
		MinPrestige = 0,
	},
	{
		Id = "mine_coal_15",
		Name = "Coal Collector",
		Description = "Mine 15 Coal blocks",
		NPC = "Miner Mike",
		Type = "Mine",
		Target = "Coal",
		Amount = 15,
		Reward = { Cash = 100 },
		MinPrestige = 0,
	},
	{
		Id = "mine_copper_10",
		Name = "Copper Rush",
		Description = "Mine 10 Copper blocks",
		NPC = "Miner Mike",
		Type = "Mine",
		Target = "Copper",
		Amount = 10,
		Reward = { Cash = 200 },
		MinPrestige = 0,
	},
	{
		Id = "sell_500",
		Name = "First Sale",
		Description = "Earn $500 from selling ores",
		NPC = "Miner Mike",
		Type = "Sell",
		Target = nil,
		Amount = 500,
		Reward = { Cash = 250 },
		MinPrestige = 0,
	},
	-- Intermediate quests
	{
		Id = "mine_iron_20",
		Name = "Iron Will",
		Description = "Mine 20 Iron blocks",
		NPC = "Miner Mike",
		Type = "Mine",
		Target = "Iron",
		Amount = 20,
		Reward = { Cash = 500 },
		MinPrestige = 0,
	},
	{
		Id = "mine_gold_10",
		Name = "Gold Digger",
		Description = "Mine 10 Gold blocks",
		NPC = "Miner Mike",
		Type = "Mine",
		Target = "Gold",
		Amount = 10,
		Reward = { Cash = 1000 },
		MinPrestige = 0,
	},
	{
		Id = "depth_100",
		Name = "Deep Diver",
		Description = "Reach depth 100",
		NPC = "Miner Mike",
		Type = "Depth",
		Target = nil,
		Amount = 100,
		Reward = { Cash = 2000 },
		MinPrestige = 0,
	},
	{
		Id = "mine_ruby_5",
		Name = "Ruby Hunter",
		Description = "Mine 5 Ruby blocks",
		NPC = "Miner Mike",
		Type = "Mine",
		Target = "Ruby",
		Amount = 5,
		Reward = { Cash = 3000 },
		MinPrestige = 0,
	},
	-- Advanced quests
	{
		Id = "depth_300",
		Name = "Into the Depths",
		Description = "Reach depth 300",
		NPC = "Miner Mike",
		Type = "Depth",
		Target = nil,
		Amount = 300,
		Reward = { Cash = 10000 },
		MinPrestige = 0,
	},
	{
		Id = "mine_rift_shard_3",
		Name = "Rift Touched",
		Description = "Mine 3 Rift Shards",
		NPC = "Miner Mike",
		Type = "Mine",
		Target = "Rift Shard",
		Amount = 3,
		Reward = { Cash = 25000 },
		MinPrestige = 0,
	},
	{
		Id = "prestige_1",
		Name = "Rebirth",
		Description = "Prestige for the first time",
		NPC = "Miner Mike",
		Type = "Prestige",
		Target = nil,
		Amount = 1,
		Reward = { Cash = 50000 },
		MinPrestige = 0,
	},
	{
		Id = "mine_void_crystal_1",
		Name = "The Void Awaits",
		Description = "Mine 1 Void Crystal",
		NPC = "Miner Mike",
		Type = "Mine",
		Target = "Void Crystal",
		Amount = 1,
		Reward = { Cash = 100000 },
		MinPrestige = 0,
	},
}

return QuestSystem
